[package]
name = "yew-example"
version = "0.1.0"
authors = ["Hugo Mota <hugo.txt@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2.67"
